docs: add sudo to the linux docs
runfinch/finch-website pull request #136
Opened 2024-11-11 18:30 UTC by pendo324

**Issue number:**

Closes #

**Description of changes:**
- Adds `sudo` to the Linux docs where appropriate
    - The commands are almost identical to macOS, but better to have slight duplication in the name of simplicity
- Adds a new optional mechanism for avoiding the use of `sudo` on Linux

**Terms of contribution:**

By submitting this pull request, I confirm that my contribution is made under
the terms of the licenses outlined in the LICENSE-SUMMARY file.

2024-11-11 19:11 UTC, chews93319 commented on docs/docs/getting-started/running-containers.md
> +    finch run \
Should this also be `sudo finch run ...`?

2024-11-11 19:18 UTC, chews93319 commented on docs/docs/getting-started/pushing-images.md
> +            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/hello-finch:latest
nit: Should this use the "more explicit" syntax including the `${ }`?

( I know that we do not necessarily require the specific string extrapolation provided by curly braces.. )

2024-11-11 19:21 UTC, chews93319 commented on docs/docs/getting-started/installation.md
> +   === "macOS/Windows"
nit: Everywhere else the three platforms are separated, but here it is combined.

Although valid, should we separate to conform to the precedence of the other pages?

2024-11-11 19:36 UTC, chews93319 requested changes
I had qty.2 "nit comments" and I think qty.1 that needs a correction.

2024-11-11 20:08 UTC, pendo324 commented on docs/docs/getting-started/pushing-images.md
> +            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/hello-finch:latest
I think we can do a find/replace and change that all at once, in another PR

2024-11-11 20:13 UTC, pendo324 commented on docs/docs/getting-started/installation.md
> +   === "macOS/Windows"
Yeah, probably doesn't hurt. Updated in latest rev

2024-11-11 20:13 UTC, pendo324 commented on docs/docs/getting-started/running-containers.md
> +    finch run \
yep, good catch, fixed in latest rev

2024-11-11 22:47 UTC, chews93319 commented on docs/docs/getting-started/pushing-images.md
> +            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/hello-finch:latest
Sounds fair to me.

2024-11-11 22:48 UTC, chews93319 commented on docs/docs/container-images/authentication.md
> +       file located at `/root/.docker/config.json`
+1

2024-11-11 22:50 UTC, chews93319 requested changes
All of my comments were addressed.
I believe that Shub noticed an additional line that requires change.

2024-11-11 22:56 UTC, Shubhranshu153 commented on docs/docs/container-images/authentication.md
> +    #### Using the AWS CLI to login to Amazon ECR
are these docs from ecr then probably we just link it, duplicate docs are hard to manage, except for finch specific config would prefer not to have extra info on the website.

2024-11-11 23:00 UTC, pendo324 commented on docs/docs/container-images/authentication.md
> +       file located at `/root/.docker/config.json`
No. This is the correct path on Linux. This is configured with the DOCKER_CONFIG environment variable, which is not overwritten on Linux: https://github.com/runfinch/finch/pull/1110

2024-11-11 23:01 UTC, pendo324 commented on docs/docs/container-images/authentication.md
> +    #### Using the AWS CLI to login to Amazon ECR
I just duplicated what we already had. We can take a followup action to remove documentation that's taken from somewhere else

2024-11-11 23:25 UTC, Shubhranshu153 approved these changes

2024-11-12 04:52 UTC, chews93319 approved these changes

2024-11-12 15:57 UTC, merged